# Generated by Django 4.2.5 on 2023-09-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_place_place_name_remove_user_place_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_place',
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='like_place',
            field=models.ManyToManyField(to='mainApp.place'),
        ),
    ]
