# Generated by Django 4.2.5 on 2023-09-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
