# Generated by Django 4.2.5 on 2023-09-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_place',
            field=models.ManyToManyField(related_name='users', to='mainApp.place'),
        ),
    ]
