# Generated by Django 4.2.5 on 2023-09-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_user_like_place_alter_gu_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_place',
            field=models.ManyToManyField(default=None, related_name='users', to='mainApp.place'),
        ),
    ]
