# Generated by Django 4.2.5 on 2023-09-30 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_user_like_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='gu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.gu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_place',
            field=models.ManyToManyField(to='mainApp.place'),
        ),
    ]
