# Generated by Django 4.2.4 on 2023-10-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_place_gu_alter_user_like_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='x_coor',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='y_coor',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
