# Generated by Django 4.2 on 2024-01-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_place_mainfood1_place_mainfood2_place_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_place',
            field=models.ManyToManyField(blank=True, to='mainApp.place'),
        ),
    ]
