# Generated by Django 4.2 on 2024-05-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_alter_place_tag_alter_user_like_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='sentence',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
